baseURL: 'http://example.org/'
defaultContentLanguage: 'zh-TW'
title: '奇蹟課程新譯'
languages:
  zh-TW:
    languageName: 'Chinese'
    contentDir: 'content'
    weight: 3
theme: 'hugo-book'
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  password: 'acim'